[eventlistener:oesap-cleanup]
command=/usr/bin/python3 /usr/local/lib/supervisor-process-cleanup.py
events=PROCESS_STATE_EXITED
priority=1
startsecs=0
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
