[unix_http_server]
file=/run/supervisor.sock
chmod=0600

[inet_http_server]
port=0.0.0.0:23231
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s

[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf
